export const myProjects = [
  {
    id: 1,
    titlePro: "Leon",
    catogray: ["html", "css"],
    img: "./images/leon.png",
    gitHup: "https://github.com/Abdullaheisa/leon",
    linkpro: "https://abdullaheisa.github.io/leon/leon.html",
  },
  {
    id: 2,
    titlePro: "Kasper",
    catogray: ["html", "css"],
    img: "./images/kasper.png",
    gitHup: "https://github.com/Abdullaheisa/Kasper",
    linkpro: "https://abdullaheisa.github.io/Kasper/kasper.html",
  },
  {
    id: 3,
    titlePro: "Dragoon",
    catogray: ["js"],
    img: "./images/dragoon.png",
    gitHup: "https://github.com/Abdullaheisa/Dragoon-tamplete-3",
    linkpro: "https://abdullaheisa.github.io/Dragoon-tamplete-3/",
  },
  {
    id: 4,
    titlePro: "Dashboard",
    catogray: ["html", "css"],
    img: "./images/dashboard.png",
    gitHup: "https://github.com/Abdullaheisa/Dragoon-tamplete-4",
    linkpro: "https://abdullaheisa.github.io/Dragoon-tamplete-4/index.html",
  },
  {
    id: 5,
    titlePro: "Learn Course",
    catogray: ["html", "css"],
    img: "./images/learnCourse.png",
    gitHup: "https://github.com/Abdullaheisa/Learn-Courses",
    linkpro: "https://abdullaheisa.github.io/Learn-Courses/",
  },
  {
    id: 6,
    titlePro: "prolex",
    catogray: ["js"],
    img: "./images/prolex.png",
    gitHup: "https://github.com/Abdullaheisa/Special-Design",
    linkpro: "https://abdullaheisa.github.io/Special-Design/",
  },
  {
    id: 7,
    titlePro: "Social Media",
    catogray: ["js"],
    img: "./images/social.png",
    gitHup: "https://github.com/Abdullaheisa/socialMedia",
    linkpro: "https://aocialmedia-website.netlify.app/",
  },
  {
    id: 8,
    titlePro: "E-comerce",
    catogray: ["js"],
    img: "./images/ecomerce.png",
    gitHup: "https://github.com/Abdullaheisa/E-commerce-with-js",
    linkpro: "https://",
  },
  {
    id: 9,
    titlePro: "Travilo",
    catogray: ["react"],
    img: "./images/travilo.png",
    gitHup: "https://github.com/Abdullaheisa/travilo/tree/master",
    linkpro: "https://abdullaheisa.github.io/travilo/",
  },
  {
    id: 10,
    titlePro: "Marvil",
    catogray: ["react"],
    img: "./images/marvil.png",
    gitHup: "https://github.com/Abdullaheisa/Marvil",
    linkpro: "https://abdullaheisa.github.io/Marvil/",
  },

];
